First pass updating to 1.8.18
- Got the patches to apply cleanly.
- Dropped a patch that was disabling logging; had conflicts and doesn't
  seem worth the maintenance burden.

UI fails to display; instead we get the error:

```
An error occurred while loading the page:

    Error: The module at "js-cookie/dist/js.cookie" does not exist.

in http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36
at line 559:15

Stack trace:

    _designatedRequire@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:559:15
    designatedRequire@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:584:74
    requireRelative@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:589:12
    require@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:622:16
    (module ep_etherpad-lite/static/js/pad_utils.js)@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=86a1ec36:1154:21
    loadModule@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:410:21
    after@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:434:21
    _find@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:446:11
    _moduleAtPath@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:452:10
    moduleAtPathSync@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:488:20
    _designatedRequire@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:556:18
    designatedRequire@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:584:74
    requireRelative@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:589:12
    require@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:622:16
    (module ep_etherpad-lite/static/js/pad.js)@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=86a1ec36:33:24
    loadModule@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:410:21
    after@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:434:21
    _find@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:446:11
    _moduleAtPath@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:452:10
    moduleAtPathSync@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:488:20
    _designatedRequire@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:556:18
    designatedRequire@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:584:74
    requireRelative@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:589:12
    require@http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/static/js/require-kernel.js?v=86a1ec36:622:16
    @http://ui-a4aff542c13c061f703d85cf0396f6c6.local.sandstorm.io:6090/p/main:914:28
```

...in the browser. More investigation is needed.